### PR TITLE
Switched to pwned passwords v2 library

### PR DESCRIPTION
**Pull request by Plazmaz**
This uses a k-anonymity model to allow for a more secure method of checking user passwords. See [this page](https://haveibeenpwned.com/API/v2#SearchingPwnedPasswordsByRange) for more info.

### CODE REVIEW

**Comment by jamiecounsell** [comment]
@Plazmaz thanks! Don't worry about the checks failing. It's Travis is choking on Python 3.5 I think, it happened with some other builds. I'll fix that, then run the checks again.

**Comment by jamiecounsell** [comment]
Hey @Plazmaz I'm going to fix the tests up and merge this

**Comment by Plazmaz** [comment]
@jamiecounsell awesome thanks

**Comment by jamiecounsell** [comment]
@Plazmaz you can now get v2.0.0 on pypi!

**Comment by Plazmaz** [comment]
@jamiecounsell awesome, thanks!

**Pull request merged**
